### ISSUE TITLE
默认配置，无法使用转发连接到xui的面板，还是必须要添加端口

### ISSUE THREAD

**Issue by suizhenmin** [wpyok500/myxray_onekey#4]
https://域名/myxui/ 无法打开 xiu面板，必须在中间添加端口 
![WX20220209-111040](https://user-images.githubusercontent.com/2957364/153114676-c70bbf93-fba4-4f7c-a630-2428fc93f228.png)

**Comment by suizhenmin** [comment]
原来是不能在面板添加证书，证书只能添加在入站节点。

**Comment by blog2020** [comment]
这一键脚本有问题，请设置面板访问端口，请输入面板端口号(默认：54321)：，请输入面板端口号(默认：54991)：，这几个端口的设置把人绕晕了，建议大佬再改改，检查检查
